repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: check-yaml
  - id: check-symlinks
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    args: [--max-line-length=100]

- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: python3 -m pytest
      language: system
      pass_filenames: false
      always_run: true
