[config]

base = "common.toml"

[solana]

address = "APFtLE6ETjxVcFCZDYcUipVQFeLPokHj53kTNTQDYe1E"
key_file = ""

[paths]

account_balances_heartbeat = "run/balances_collector_treasury/heartbeat"

[balance_collector]

watch_symbols = ["MNGO", "SOL", "MSOL", "USDC", "ETH", "USDT", "FTT", "SRM", "COPE"]
stale_data_pauses_before_retry = 2
collection_interval_seconds = 1800
heartbeat_enabled = false
