[config]

base = "common.toml"

[solana]

address = "G8kHCcbsHL5hwGYWeGJNPxti65kW6PKiiVKoKKUfHbch"
key_file = "/srv/key/mango-explorer/mu1/G8kHCcbsHL5hwGYWeGJNPxti65kW6PKiiVKoKKUfHbch.json"

[paths]

account_balances_heartbeat = "run/balances_collector_serum_msolsol/heartbeat"

[balance_collector]

stale_data_pauses_before_retry = 2
