[config]

base = "common.toml"

[solana]

#cluster_url = "https://6b45a2f5-6b33-4c12-ad6e-d6b79a584698.solana.bison.run/rpc"
address = "3rDvpyGwZcS6U9Ev5LCKM9EvbK3wWtp9sF8eCsysQevF"
key_file = "/srv/key/mango-explorer/mu1/3rDvpyGwZcS6U9Ev5LCKM9EvbK3wWtp9sF8eCsysQevF.json"

[paths]

account_balances_heartbeat = "run/balances_collector_mango_copeusdc/heartbeat"

[balance_collector]

watch_markets = ["COPE/USDC"]
stale_data_pauses_before_retry = 2
collection_interval_seconds = 1800
