[config]

base = "common.toml"

[solana]

#cluster_url = "https://mango.rpcpool.com/946ef7337da3f5b8d3e4a34e7f88"
address = "Hquj2QqZAcMDwYYTuhFW1WY4a48zi7MvGc7bJ8FvZMAU"
key_file = "/srv/key/mango-explorer/mu1/Hquj2QqZAcMDwYYTuhFW1WY4a48zi7MvGc7bJ8FvZMAU.json"

[paths]

account_balances_heartbeat = "run/balances_collector_mango_fttusdc/heartbeat"

[balance_collector]

watch_markets = ["FTT/USDC"]
collection_interval_seconds = 1800
heartbeat_enabled = false
stale_data_pauses_before_retry = 2
