[config]

base = "common.toml"

[solana]

cluster_url = "https://falling-aged-flower.solana-mainnet.quiknode.pro/63ca6516821bd013d3d4cd28a1e872509af0d14b/"
address = "DXduaJGTVVZLeTy75wDu3CkbEzsA3jFBaTHRvF4UoTyz"
key_file = "/srv/key/mango-explorer/mu1/DXduaJGTVVZLeTy75wDu3CkbEzsA3jFBaTHRvF4UoTyz.json"


[paths]

account_balances_heartbeat = "run/balances_collector_mango_solusdc/heartbeat"

[balance_collector]

watch_markets = ["SOL/USDC"]
stale_data_pauses_before_retry = 2
