[config]

base = "common.toml"

[solana]

address = "Hquj2QqZAcMDwYYTuhFW1WY4a48zi7MvGc7bJ8FvZMAU"
key_file = "/srv/key/mango-explorer/mu1/Hquj2QqZAcMDwYYTuhFW1WY4a48zi7MvGc7bJ8FvZMAU.json"

[paths]

account_balances_heartbeat = "run/balances_collector_mango_ethusdc/heartbeat"

[balance_collector]

watch_markets = ["ETH/USDC", "FTT/USDC"]
stale_data_pauses_before_retry = 2
collection_interval_seconds = 1800
heartbeat_enabled = false
