[database]

prefix = "solana_trader_"
instance_prefix = "mu1_"
dashboard_url = "postgresql://aave2-sensor:8823rfjadfbl$%$$avsdkoo1@localhost:5432/dashboard"

[solana]

cluster_url = "https://solana-rpc.rbf.systems:18899"
# marinade original API url https://api.marinade.finance/msol/price_sol, it's cached at production servers
marinade_api_url = "http://localhost:8081/msol/price_sol"
key_file = "/srv/key/mango-explorer/mu1.json"

[paths]

# paths are automatically prefixed by PREFIX environment variable
# or /srv if undefined

tmpdir = "data/tmp"  # to be changed
datadir = "data/solana"
