[config]

base = "common.toml"

[account]

cluster_url = "https://falling-aged-flower.solana-mainnet.quiknode.pro/63ca6516821bd013d3d4cd28a1e872509af0d14b/"
address = "9pWVzCbuM1EnVRDqjUUWjEL3bV6qWLSxDfx7FtQNwUyL"
key_file = "/srv/key/mango-explorer/mu1/9pWVzCbuM1EnVRDqjUUWjEL3bV6qWLSxDfx7FtQNwUyL.json"
watch_markets = ["SOL-PERP"]

[paths]

trader_heartbeat_dir = "run/solana_trader_mango_solperp"
account_balances_heartbeat = "run/balances_collector_mango_solperp/heartbeat"


[marketmaker]

pair = "SOL-PERP"
min_quote_size = "2"
spread_ratio = "0.0008"
position_size_ratios = ["0.4", "0.4"]
oracle_providers = ["pyth", "ftx"]
# price_weights determines the weight of oracles in calculating fair price
price_weights = ["0.25", "0.25"]
ewma_halflife = 300
existing_order_price_tolerance = "0.0005"
existing_order_quantity_tolerance = "0.3"
confidence_interval_level = [1]
leverage = "5"
poll_interval_seconds = 5
