[config]

base = "common.toml"

[account]

cluster_url = "https://falling-aged-flower.solana-mainnet.quiknode.pro/63ca6516821bd013d3d4cd28a1e872509af0d14b/"
address = "DXduaJGTVVZLeTy75wDu3CkbEzsA3jFBaTHRvF4UoTyz"
key_file = "/srv/key/mango-explorer/mu1/DXduaJGTVVZLeTy75wDu3CkbEzsA3jFBaTHRvF4UoTyz.json"
watch_markets = ["SOL/USDC"]

[paths]

trader_heartbeat_dir = "run/solana_trader_mango_solusdc"
account_balances_heartbeat = "run/balances_collector_mango_solusdc/heartbeat"

[marketmaker]

pair = "SOL/USDC"
min_quote_size = "2"
spread_ratio = "0.0008"
position_size_ratios = ["0.2", "0.2"]
oracle_providers = ["ftx"]
# price_weights determines the weight of oracles in calculating fair price
price_weights = [1]
existing_order_price_tolerance = "0.0005"
existing_order_quantity_tolerance = "0.3"
confidence_interval_level = [1]
leverage = "3.5"
poll_interval_seconds = 5
