[config]

base = "common.toml"

[solana]

address = "DXduaJGTVVZLeTy75wDu3CkbEzsA3jFBaTHRvF4UoTyz"

[paths]
# paths are automatically prefixed by PREFIX environment variable
price_collector_heartbeat = 'run/mango_price_collector/heartbeat'

[price_collector]
server_name = "mu1"
pause_duration = 5
# number of observation per file
max_number_of_observations = 1000
stale_data_pauses_before_retry = 3

        # symbols are pairs of oracle name and symbols queried from given oracle.
        [price_collector.symbols]
        FTX = [
            "SOL-PERP", "SOL/USD", "SOL/USDT", "SOL/BTC",
            "MNGO-PERP", "MNGO/USD",
            "BTC/USD", "BTC/USDT", "BTC/EUR", "BTC-PERP",
            "ETH/USD", "ETH/USDT", "ETH/BTC", "ETH-PERP",
            "USDT/USD", "USDT-PERP",
            "SRM/USD", "SRM/USDT", "SRM-PERP",
            "RAY/USD", "RAY-PERP",
            "COPE/USD",
            "FTT/USD", "FTT-PERP",
            "AVAX/USD", "AVAX-PERP",
            "LUNA-PERP",
            "ADA-PERP",
            "BNB/USD", "BNB-PERP",
        ]
        PYTH = [
            "MNGO/USD", "BTC/USD", "ETH/USD", "SOL/USD",
            "USDT/USD", "SRM/USD", "RAY/USD",
            "COPE/USD",
        ]
        RAYDIUM_trades = [
#            "MNDE-mSOL", "ETH-SRM", "stSOL-USDC", "RAY-ETH", "xCOPE-USDC", "RAY-SOL",
#            "BTC-SRM", "RAY-SRM", "SRM-SOL", "LARIX-RAY",  "mSOL-RAY",
            "SOL-USDC", "BTC-USDC", "RAY-USDC", "ETH-USDC", "SRM-USDC",
            "SOL-USDT", "BTC-USDT", "RAY-USDT", "ETH-USDT", "SRM-USDT",
            "ETH-SOL", "USDT-USDC", "COPE-USDC",
#            "mSOL-SOL", "mSOL-USDC"
        ]
        BINANCE_mid = [
            'PERPBTC', 'PERPBUSD', 'PERPUSDT',
            'SOLBTC', 'SOLUSDT', 'SOLEUR', 'SOLRUB', 'SOLUSDC', 'SOLETH',
            'BTCUSDT', 'BTCUSDC', 'BTCEUR',
            'ETHEUR', 'ETHUSDT', 'ETHUSDC',
            'USDCUSDT',
            'SRMBTC', 'SRMBUSD', 'SRMUSDT',
            'RAYBUSD', 'RAYUSDT',
            "AVAXUSDT",
            "LUNAUSDT",
            "ADAUSDT",
        ]
        KRAKEN_mid = [
            'PERP/EUR', 'PERP/USD',
            'SOL/EUR', 'SOL/USD',
            'BTC/USD', 'BTC/EUR',
            'WBTC/EUR', 'WBTC/USD', 'TBTC/ETH', 'TBTC/USD', 'TBTC/EUR',
            'ETH/EUR', 'ETH/USD', 'ETH/USDC', 'ETH/USDT',
            'USDC/USD', 'USDC/USDT',
            'SRM/EUR', 'SRM/USD',
            'RAY/EUR', 'RAY/USD'
        ]
