[config]

base = "common.toml"

[account]

cluster_url = "https://falling-aged-flower.solana-mainnet.quiknode.pro/63ca6516821bd013d3d4cd28a1e872509af0d14b/"
address = "7nmgeDXsyJLB9Re9bM2z7n5RsYhxgeoWUWes8yJAtZja"
key_file = "/srv/key/mango-explorer/mu1/7nmgeDXsyJLB9Re9bM2z7n5RsYhxgeoWUWes8yJAtZja.json"
watch_markets = ["SRM/USDC"]

[paths]

trader_heartbeat_dir = "run/solana_trader_mango_srmusdc"
account_balances_heartbeat = "run/balances_collector_mango_srmusdc/heartbeat"

[marketmaker]

pair = "SRM/USDC"
min_quote_size = "100"
spread_ratio = "0.0012"
spread_narrowing_coef = "0.5"
position_size_ratios = ["0.3", "0.3"]
oracle_providers = ["ftx", "kraken"]
# price_weights determines the weight of oracles in calculating fair price
price_weights = ["0.25", "0.25"]
existing_order_price_tolerance = "0.0005"
existing_order_quantity_tolerance = "0.3"
confidence_interval_level = [1]
leverage = "3"
poll_interval_seconds = 5
