[config]

base = "common.toml"

[account]

cluster_url = "https://falling-aged-flower.solana-mainnet.quiknode.pro/63ca6516821bd013d3d4cd28a1e872509af0d14b/"
address = "F4GJdmdUZHtBxMuXpLdC7g6bUiQ8XBK7tTBfJSvBjruo"
key_file = "/srv/key/mango-explorer/mu1/F4GJdmdUZHtBxMuXpLdC7g6bUiQ8XBK7tTBfJSvBjruo.json"
watch_markets = ["RAY/USDC"]
watch_symbols = ["MSOL", "RAY", "USDC"]

[paths]

trader_heartbeat_dir = "run/solana_trader_mango_rayusdc_2"
account_balances_heartbeat = "run/balances_collector_mango_rayusdc_2/heartbeat"

[marketmaker]

pair = "RAY/USDC"
min_quote_size = "0.4"
spread_ratio = "0.0012"
position_size_ratios = ["0.2", "0.2"]
# oracle_providers determine which oracles are used for MM, to get fair price
oracle_providers = ["kraken"]
# price_weights determines the weight of oracles in calculating fair price
price_weights = ["1"]
# oracle_coefs does not determine weight of oracles, but the weight of combined oracles
existing_order_price_tolerance = "0.0005"
existing_order_quantity_tolerance = "0.3"
confidence_interval_level = [1]
leverage = "3.5"
poll_interval_seconds = 5
