[config]

base = "common.toml"

[account]

#cluster_url = "https://falling-aged-flower.solana-mainnet.quiknode.pro/63ca6516821bd013d3d4cd28a1e872509af0d14b/"
#cluster_url_wss = "wss://falling-aged-flower.solana-mainnet.quiknode.pro/63ca6516821bd013d3d4cd28a1e872509af0d14b/"
#cluster_url = "https://ssc-dao.genesysgo.net/"
#cluster_url_wss = "wss://ssc-dao.genesysgo.net"
cluster_url = 'http://solana-rpc.rbf.systems:8899/'
cluster_url_wss = 'ws://solana-rpc.rbf.systems:8900'

address = "G8kHCcbsHL5hwGYWeGJNPxti65kW6PKiiVKoKKUfHbch"
key_file = "/srv/key/mango-explorer/mu1/G8kHCcbsHL5hwGYWeGJNPxti65kW6PKiiVKoKKUfHbch.json"
orca_proxy_url = "http://localhost:1080"
watch_markets = ["MSOL/USDC", "SERUM:SOL/USDC", "MSOL/SOL"]
watch_symbols = ["ETH", "USDT", "FTT", "SRM", "COPE"]

[paths]

trader_heartbeat_dir = "run/solana_trader_serum_msolusdc"
account_balances_heartbeat = "run/balances_collector_serum_msolusdc/heartbeat"
saber_arbitrage_heartbeat = "/run/arbitrage/saber_heartbeat"
orca_arbitrage_heartbeat = "/run/arbitrage/orca_heartbeat"

# [marketmaker]

# pair = "MSOL/USDC"
# min_quote_size = "0.5"
# spread_ratio = "0.0005"
# position_size_ratios = ["0", "0.9"]
# oracle_providers = ["ftx"]
# price_weights determines the weight of oracles in calculating fair price
# price_weights = [1]
# oracle_coefs = ["0.5"]
# existing_order_tolerance = "0.0002"
# confidence_interval_level = [1]
# leverage = 1
# poll_interval_seconds = 10

[marinade_staking]

delay_after_staking_seconds = 5
# staking is turned on when staking_on = "True"
staking_on = "False"
config_path = "/srv/app/mango-explorer/cfg/mu1/marinade_staking.yaml"
poll_interval_seconds = 1
min_staking_quantity = "0.1"
keep_amount_sol = "0.2"
wsol_address = "HSgLxLUF3zTNVFzgQjKXpt9aKhf1m9wmyaYCMRFpaYUn"


[saber_arbitrage]

[saber_arbitrage.msolsol]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "MSOL/SOL"
saber_symbol = "mSOL-SOL"
oracle_provider_name = "msol"
min_trade_size = "0.1"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.0001"
threshold_relative_quantity = "0.0005"


# TODO: rename "simplearbitrage" to "orca_arbitrage" a add one layer between
# "root" and orca_arbitrage called
[simplearbitrage]

[simplearbitrage.msolusdc]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "MSOL/USDC"
orca_symbol = "mSOL_USDC"
oracle_provider_name = "serum"
min_trade_size = "0.1"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

[simplearbitrage.msolusdt]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "MSOL/USDT"
orca_symbol = "mSOL_USDT"
oracle_provider_name = "ftx"
min_trade_size = "0.1"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

[simplearbitrage.msolsol]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "MSOL/SOL"
orca_symbol = "mSOL_SOL"
oracle_provider_name = "msol"
min_trade_size = "0.1"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

[simplearbitrage.solusdc]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "SOL/USDC"
orca_symbol = "SOL_USDC"
oracle_provider_name = "serum"
min_trade_size = "0.1"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

[simplearbitrage.solusdt]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "SOL/USDT"
orca_symbol = "SOL_USDT"
oracle_provider_name = "serum"
min_trade_size = "0.1"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

[simplearbitrage.fttusdc]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "FTT/USDC"
orca_symbol = "FTT_USDC"
oracle_provider_name = "ftx"
min_trade_size = "0.1"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

[simplearbitrage.fttsol]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "FTT/SOL"
orca_symbol = "FTT_SOL"
oracle_provider_name = "ftx"
min_trade_size = "0.1"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

[simplearbitrage.copeusdc]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "COPE/USDC"
orca_symbol = "COPE_USDC"
oracle_provider_name = "ftx"
min_trade_size = "3"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

[simplearbitrage.copesol]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "COPE/SOL"
orca_symbol = "COPE_SOL"
oracle_provider_name = "ftx"
min_trade_size = "3"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

[simplearbitrage.ethusdc]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "ETH/USDC"
orca_symbol = "ETH_USDC"
oracle_provider_name = "binance"
min_trade_size = "0.005"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"


[simplearbitrage.ethsol]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "ETH/SOL"
orca_symbol = "ETH_SOL"
oracle_provider_name = "ftx"
min_trade_size = "0.005"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

[simplearbitrage.srmsol]

poll_interval_seconds = 1
delay_after_arbitrage_seconds = 15
market_symbol = "SRM/SOL"
orca_symbol = "SRM_SOL"
oracle_provider_name = "ftx"
min_trade_size = "3"
position_size_ratios = ["0.2", "0.2"]
profitability_scaling_size = "2"
profitable_relative_deviation = "0.004"
threshold_relative_quantity = "0.0005"

#[simplearbitrage.orcausdc]

#poll_interval_seconds = 1
#delay_after_arbitrage_seconds = 15
#market_symbol = "ORCA/USDC"
#orca_symbol = "ORCA_USDC"
#oracle_provider_name = "serum"
#min_trade_size = "0.1"
#position_size_ratios = ["0.2", "0.2"]
#profitability_scaling_size = "2"
#profitable_relative_deviation = "0.004"
#threshold_relative_quantity = "0.0005"

#[simplearbitrage.orcasol]

#poll_interval_seconds = 1
#delay_after_arbitrage_seconds = 15
#market_symbol = "ORCA/SOL"
#orca_symbol = "ORCA_SOL"
#oracle_provider_name = "serum"
#min_trade_size = "0.1"
#position_size_ratios = ["0.2", "0.2"]
#profitability_scaling_size = "2"
#profitable_relative_deviation = "0.004"
#threshold_relative_quantity = "0.0005"

#[simplearbitrage.orcamsol]

#poll_interval_seconds = 1
#delay_after_arbitrage_seconds = 15
#market_symbol = "ORCA/MSOL"
#orca_symbol = "ORCA_mSOL"
#oracle_provider_name = "serum"
#min_trade_size = "0.1"
#position_size_ratios = ["0.2", "0.2"]
#profitability_scaling_size = "2"
#profitable_relative_deviation = "0.004"
#threshold_relative_quantity = "0.0005"
